FROM python:3.9-alpine
RUN apk add --update gcc python3-dev libffi-dev musl-dev && \
    pip3 wheel --wheel-dir=/srv/wheels pip 'devpi-server==6.4.0' 'devpi-client==5.2.3' 'devpi-web==4.0.8' 'devpi-semantic-ui==0.2.2'

FROM python:3.9-alpine
COPY --from=0 /srv/wheels /srv/wheels
VOLUME /srv/devpi
ENV DEVPISERVER_SERVERDIR=/var/lib/devpi
ENV SOURCE_MIRROR_URL=https://pypi.douban.com/simple
RUN pip3 install --no-cache-dir --no-index --find-links=/srv/wheels devpi-server devpi-client devpi-web devpi-semantic-ui
COPY entrypoint.sh /srv/entrypoint.sh
LABEL maintainer="LowinLi <lowinli@outlook.com>"
ENTRYPOINT ["/srv/entrypoint.sh"]